version: '3.8'

services:
  app:
    build: .
    deploy:
      replicas: 1
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 1s
      retries: 1
      start_period: 1s
      start_interval: 1s
    networks:
      - app
  redis:
    image: redis
    volumes:
      - redis:/data
    networks:
      - app

volumes:
  redis:

# Criando uma nova network
networks:
  app:

# Usando uma network ja existente
# Lembre-se de comentar a network criada acima
# docker network create app
# networks:
#   app:
    # name: app
    # external: true