version: '3.8'

services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis: