version: '3.8'

services:
  app:
    build: .
    deploy:
      replicas: 2
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 1s
      retries: 1
      start_period: 1s
      start_interval: 1s
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis: